import '/imports/client/custom/vq/templates/add_attribute_form.js'
import '/imports/client/custom/vq/templates/add_class_name_form.js'
import '/imports/client/custom/vq/templates/add_condition_form.js'
import '/imports/client/custom/vq/templates/add_link_form.js'
import '/imports/client/custom/vq/templates/add_merge_form.js'
import '/imports/client/custom/vq/templates/add_uri_form.js'
import '/imports/client/custom/vq/templates/aggregate_wizard_form.js'
import '/imports/client/custom/vq/templates/class_conditions_form.js'
import '/imports/client/custom/vq/templates/connect_classes_form.js'
import '/imports/client/custom/vq/templates/dump.js'
import '/imports/client/custom/vq/templates/explain_field_form.js'
import '/imports/client/custom/vq/templates/explain_link_form.js'
import '/imports/client/custom/vq/templates/sparql_form.js'
import '/imports/client/custom/vq/templates/SchemaTree.js'

// import '/imports/client/custom/vq/templates/add_subquery_form.html'
import '/imports/client/custom/vq/templates/ajoo_bkus.html'
import '/imports/client/custom/vq/templates/loginBranding.html'
