import '/imports/custom/vq/client/templates/add_attribute_form.js'
import '/imports/custom/vq/client/templates/add_class_name_form.js'
import '/imports/custom/vq/client/templates/add_condition_form.js'
import '/imports/custom/vq/client/templates/add_link_form.js'
import '/imports/custom/vq/client/templates/add_merge_form.js'
import '/imports/custom/vq/client/templates/add_uri_form.js'
import '/imports/custom/vq/client/templates/aggregate_wizard_form.js'
import '/imports/custom/vq/client/templates/class_conditions_form.js'
import '/imports/custom/vq/client/templates/class_attributes_form.js'
import '/imports/custom/vq/client/templates/connect_classes_form.js'
import '/imports/custom/vq/client/templates/dump.js'
import '/imports/custom/vq/client/templates/explain_field_form.js'
import '/imports/custom/vq/client/templates/explain_link_form.js'
import '/imports/custom/vq/client/templates/sparql_form.js'
import '/imports/custom/vq/client/templates/SchemaTree.js'
import '/imports/custom/vq/client/templates/VQ_DSS_schema.js'
import '/imports/custom/vq/client/templates/VQ_DSS_custom_sparql.js'
import '/imports/custom/vq/client/templates/fragments.js'
import '/imports/custom/vq/client/templates/VQ_top_level_forms.js'
import '/imports/custom/vq/client/templates/generate_complex_table_query_form.js'

import '/imports/custom/vq/client/templates/import_diagram_dialogs.html'

// import '/imports/custom/vq/client/templates/add_subquery_form.html'
import '/imports/custom/vq/client/templates/ajoo_bkus.html'
// import '/imports/custom/vq/client/templates/loginBranding.html'
import '/imports/custom/vq/client/templates/loginBranding.js'
